In [1]:
import numpy as np

# 1.创建一个一维数组，其中包含1~20的奇数；再使用数组的维度变换方法，改变原数组形状为[2,5]。

In [2]:
a = np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [3]:
a.resize(2,5)
a

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

# 2.打印消息“The first three items in the list are:”，再使用切片来打印列表的前三个元素。

In [4]:
b = "The first three items in the list are:"
print(b)

The first three items in the list are:


In [5]:
print(b[:3])

The


# 3.创建一个行值是从0到4的5*5矩阵。

In [6]:
c = np.zeros((5,5))
c += np.arange(5)
print(c)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 4.创建一个对角线（diagonal）下面是1,2,3,4的5*5矩阵。

In [7]:
d = np.diag(1+np.arange(4),k=-1)
print(d)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 5.创建一个10*10的随机数组并查找最大最小值。

In [8]:
E = np.random.random((10,10))
E

array([[0.64000226, 0.32893049, 0.57469507, 0.7191154 , 0.84100055,
        0.10414892, 0.70004419, 0.08924108, 0.04453418, 0.53140052],
       [0.12709132, 0.49618423, 0.80665231, 0.50480773, 0.0342399 ,
        0.08028302, 0.60867626, 0.55677295, 0.81186437, 0.58190838],
       [0.83437017, 0.04118441, 0.75503501, 0.7560931 , 0.12077955,
        0.34110712, 0.83471468, 0.07324817, 0.27553888, 0.09529068],
       [0.34515205, 0.05110367, 0.83686197, 0.13534996, 0.30298594,
        0.5517438 , 0.84727915, 0.91152951, 0.59529865, 0.14509532],
       [0.25254879, 0.10653083, 0.07212028, 0.52230379, 0.87915047,
        0.8033173 , 0.53224277, 0.71876382, 0.46924102, 0.33132685],
       [0.39818848, 0.80458679, 0.72373638, 0.72545203, 0.45828573,
        0.47545804, 0.25960666, 0.52620389, 0.00294236, 0.73452085],
       [0.9822478 , 0.18000302, 0.19843541, 0.96849403, 0.41981219,
        0.89529263, 0.91658614, 0.12578417, 0.19256023, 0.63502111],
       [0.7893636 , 0.99558114, 0.4802838

In [9]:
Emin, Emax = E.min(), E.max()
print (Emin, Emax)

0.0029423555303053073 0.9955811435606219
