In [1]:
import numpy as np
a = np.array([[0,1,2,3,4],
             [9,8,7,6,5]])
a

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [2]:
print(a)

[[0 1 2 3 4]
 [9 8 7 6 5]]


In [3]:
import numpy as np
np.random.seed(0) # 设置随机数种子

x1 = np.random.randint(10, size=6) # 一维数组
x2 = np.random.randint(10, size=(3, 4))# 二维数组
x3 = np.random.randint(10, size=(3, 4, 5))# 三维数组

In [4]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size:", x3.size)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size: 60


In [5]:
print("dtype:", x3.dtype)

dtype: int64


In [6]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [7]:
x = np.array([0,1,2,3])

In [8]:
print(x)

[0 1 2 3]


In [9]:
x = np.array((4,5,6,7))
print(x)

[4 5 6 7]


In [10]:
x = np.array(([1,2],[8,9],
             [0.1,0.2]))
print(x)

[[1.  2. ]
 [8.  9. ]
 [0.1 0.2]]


In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
np.zeros((4,5),dtype = np.int32)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
x = np.ones((2,3))

In [16]:
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
x.shape

(2, 3)

In [18]:
a = np.linspace(1,10,4)
a

array([ 1.,  4.,  7., 10.])

In [19]:
b = np.linspace(1,10,4,endpoint=False)
b

array([1.  , 3.25, 5.5 , 7.75])

In [20]:
c = np.concatenate((a,b))
c

array([ 1.  ,  4.  ,  7.  , 10.  ,  1.  ,  3.25,  5.5 ,  7.75])

In [21]:
grid = np.arange(1, 10).reshape((3, 3)) 
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
x = np.array([1, 2, 3])

# 通过变形获得的行向量 
x.reshape((1, 3))

array([[1, 2, 3]])

In [23]:
# 通过newaxis获得的行向量 
x[np.newaxis, :]

array([[1, 2, 3]])

In [24]:
# 通过变形获得的列向量 
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [25]:
# 通过newaxis获得的列向量 
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [26]:
arr = np.arange(6).reshape((2,3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
np.transpose(arr)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [28]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [29]:
arr.swapaxes(0,1)

array([[0, 3],
       [1, 4],
       [2, 5]])

In [30]:
x1

array([5, 0, 3, 3, 7, 9])

In [31]:
x1[0]

5

In [32]:
x1[4]

7

In [33]:
x1[-1]

9

In [34]:
x1[-2]

7

In [35]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [36]:
x2[0,0]

3

In [37]:
x2[2,0]

1

In [38]:
x2[2,-1]

7

In [39]:
x1[0] = 3.14159
x1

array([3, 0, 3, 3, 7, 9])

In [40]:
x = np.arange(10) 
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[:5] # 前五个元素

array([0, 1, 2, 3, 4])

In [42]:
x[5:] # 索引五之后的元素

array([5, 6, 7, 8, 9])

In [43]:
x[4:7] # 中间的子数组

array([4, 5, 6])

In [44]:
x[::2] # 每隔一个元素

array([0, 2, 4, 6, 8])

In [45]:
x[1::2] # 每隔一个元素，从索引1开始

array([1, 3, 5, 7, 9])

In [46]:
x[::-1] # 所有元素，逆序的

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [47]:
x[5::-2] # 从索引5开始每隔一个元素逆序

array([5, 3, 1])

In [48]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [49]:
x2[:3, ::2] # 所有行，每隔一列

array([[3, 2],
       [7, 8],
       [1, 7]])

In [50]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

In [51]:
print(x2[:, 0]) # x2的第一列

[3 7 1]


In [52]:
print(x2[0, :]) # x2的第一行

[3 5 2 4]


In [53]:
print(x2[0])

[3 5 2 4]


In [54]:
x = np.array([1, 2, 3]) 
y = np.array([3, 2, 1]) 
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [55]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [56]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [57]:
# 沿着第一个轴拼接 
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [58]:
# 沿着第二个轴拼接（从0开始索引） 
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [59]:
x = np.array([1,2,3])
grid = np.array([[9,8,7],
                 [6,5,4]])
# 垂直栈数组
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [60]:
# 水平栈数组
y = np.array([[99],
              [99]]) 
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [61]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5]) 
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [62]:
grid = np.arange(16).reshape((4, 4)) 
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [63]:
upper, lower = np.vsplit(grid, [2]) 
print(upper) 
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [64]:
left, right = np.hsplit(grid, [2]) 
print(left) 
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [65]:
a = np.arange(100).reshape(5,20)

In [66]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [67]:
np.savetxt('a.csv',a,fmt='%1f',delimiter=',')

In [68]:
b = np.loadtxt('a.csv',delimiter=',')
b

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
        13., 14., 15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24., 25., 26., 27., 28., 29., 30., 31., 32.,
        33., 34., 35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
        53., 54., 55., 56., 57., 58., 59.],
       [60., 61., 62., 63., 64., 65., 66., 67., 68., 69., 70., 71., 72.,
        73., 74., 75., 76., 77., 78., 79.],
       [80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91., 92.,
        93., 94., 95., 96., 97., 98., 99.]])

In [69]:
a = np.arange(50).reshape(5,10)
a.tofile("b.dat",sep=",",format='%d')

In [70]:
c = np.fromfile("b.dat",dtype=np.int,sep=",")
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [71]:
c = np.fromfile("b.dat",dtype=np.int,sep=",").reshape(5,10)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [72]:
a = np.arange(50).reshape(5,10)
np.save("a.npy",a)

In [73]:
b = np.load("a.npy")
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [74]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [75]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [76]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [77]:
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta) 
print("sin(theta) = ", np.sin(theta)) 
print("cos(theta) = ", np.cos(theta)) 
print("tan(theta) = ", np.tan(theta))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [78]:
x = [-1, 0, 1]
print("x = ", x)
print("arcsin(x) = ", np.arcsin(x)) 
print("arccos(x) = ", np.arccos(x)) 
print("arctan(x) = ", np.arctan(x))

x =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [79]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [80]:
x = [1, 2, 4, 10]
print("x =", x) 
print("ln(x) =", np.log(x)) 
print("log2(x) =", np.log2(x)) 
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [81]:
a = np.random.rand(3,4)
a

array([[0.65279032, 0.63505887, 0.99529957, 0.58185033],
       [0.41436859, 0.4746975 , 0.6235101 , 0.33800761],
       [0.67475232, 0.31720174, 0.77834548, 0.94957105]])

In [82]:
sn = np.random.randn(3,4)
sn

array([[ 1.50944508,  1.06777513, -0.68658948,  0.01487332],
       [-0.3756659 , -0.03822364,  0.36797447, -0.0447237 ],
       [-0.30237513, -2.2244036 ,  0.72400636,  0.35900276]])

In [83]:
b = np.random.randint(100,200,(3,4))
b

array([[194, 167, 182, 146],
       [199, 120, 181, 150],
       [127, 114, 141, 158]])

In [84]:
u = np.random.uniform(0,10,(3,4))
u

array([[5.75946496, 9.29296198, 3.18568952, 6.6741038 ],
       [1.31797862, 7.16327204, 2.89406093, 1.83191362],
       [5.86512935, 0.20107546, 8.28940029, 0.04695476]])

In [85]:
n = np.random.normal(10,5,(3,4))
n

array([[ 4.1742508 , 14.50413243, 12.3283122 ,  2.31878157],
       [17.44126097, 19.47944588, 15.89389786,  9.10037582],
       [ 4.64623689, 15.27225863,  7.98411527, 16.11222535]])

In [86]:
L = np.random.random(100) 
sum(L)

50.633609290233096

In [87]:
np.sum(L)

50.633609290233096

In [88]:
big_array = np.random.rand(1000000)
min(big_array), max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [89]:
np.min(big_array), np.max(big_array)

(7.071203171893359e-07, 0.9999997207656334)

In [90]:
%timeit min(big_array) 
%timeit np.min(big_array)

142 ms ± 14.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
730 µs ± 85.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [91]:
print(big_array.min(), big_array.max(), big_array.sum())

7.071203171893359e-07 0.9999997207656334 500386.40657977166


In [92]:
M = np.random.random((3, 4)) 
print(M)

[[0.23063821 0.29099865 0.50482554 0.48470031]
 [0.40046709 0.28257198 0.54703087 0.82385379]
 [0.25444533 0.18997011 0.00158799 0.53134718]]


In [93]:
M.sum()

4.542437049254397

In [94]:
M.min(axis=0)

array([0.23063821, 0.18997011, 0.00158799, 0.48470031])

In [95]:
M.max(axis=1)

array([0.50482554, 0.82385379, 0.53134718])

In [96]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.where(b > 5)

(array([6, 7, 8, 9]),)

In [98]:
a = np.arange(20).reshape(4,5)

In [99]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [100]:
np.where(a > 10)

(array([2, 2, 2, 2, 3, 3, 3, 3, 3]), array([1, 2, 3, 4, 0, 1, 2, 3, 4]))

In [101]:
a = np.random.randint(0,5,8)
a

array([3, 3, 3, 4, 2, 4, 0, 3])

In [102]:
np.unique(a)

array([0, 2, 3, 4])

In [103]:
rng = np.random.RandomState(0) 
x = rng.randint(10, size=(3, 4)) 
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [104]:
x < 6

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [ True,  True, False, False]])

In [105]:
# 有多少值小于6？ 
np.count_nonzero(x < 6)

8

In [106]:
np.sum(x < 6)

8

In [107]:
# 每行有多少值小于6？ 
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [108]:
# 有没有值大于8？ 
np.any(x > 8)

True

In [109]:
# 有没有值小于0？
np.any(x < 0)

False

In [110]:
# 是否所有值都小于10？
np.all(x < 10)

True

In [111]:
# 是否所有值都等于6？ 
np.all(x == 6)

False

In [112]:
# 是否每行的所有值都小于8？ 
np.all(x < 8, axis=1)

array([ True, False,  True])

In [113]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [114]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]])

In [115]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

In [116]:
x = np.array([2, 1, 4, 3, 5]) 

In [117]:
np.sort(x)

array([1, 2, 3, 4, 5])

In [118]:
x.sort() 
print(x)

[1 2 3 4 5]


In [119]:
x = np.array([2, 1, 4, 3, 5]) 
i = np.argsort(x) 
print(i)

[1 0 3 2 4]


In [120]:
rand = np.random.RandomState(42) 
X = rand.randint(0, 10, (4, 6)) 
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [121]:
# 对X的每一列排序 
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [122]:
# 对X每一行排序 
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [123]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [124]:
np.partition(X, 2, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [125]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

In [126]:
x = np.zeros(4, dtype=int)
# 使用复合数据结构的结构化数组
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 
                          'formats':('U10', 'i4', 'f8')}) 
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [127]:
data['name'] = name
data['age'] = age 
data['weight'] = weight 
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [128]:
# 获取所有名字 
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [129]:
# 获取数据第一行 
data[0]

('Alice', 25, 55.)

In [130]:
# 获取最后一行的名字 
data[-1]['name']

'Doug'

In [131]:
# 获取年龄小于30岁的人的名字 
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [132]:
np.dtype({'names':('name', 'age', 'weight'), 
          'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [133]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])